export const PATH = {
    MAIN: "/",
    PLACES: "/places",
    PLACE: "/place/",
    PLACE_AREAS: "/place/areas/",
    PLACE_AREAS_CREATE: "/place/areas/create",
    SEAT: "/place/seats/",
    PERFORMANCES: "/performances",
    PERFORMANCE_CREATE: "/performance/create",
    PERFORMANCE_EDIT: "/performance/edit/",
    PERFORMANCE_CAST: "/performance/cast/",
    PERFORMANCE_SEAT: "/performance/seat/",
    PERFORMANCE_SCHEDULE: "/performance/schedule/",
    PERFORMANCE_CONTENT: "/performance/content/",
}